version: '3.8'
# -=-=-=-=-=-=-=-=-=-=VOLUMES=-=-=-=-=-=-=-=-=-=-
volumes:
  data:
# -=-=-=-=-=-=-=-=-=-=NETWORKS=-=-=-=-=-=-=-=-=-=-
networks:
  backend:
    ipam:
      config:
        - subnet: 172.23.0.0/16
services:
  # -=-=-=-=-=-=-=-=-=-=FRONTEND=-=-=-=-=-=-=-=-=-=-
  front:
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: ./front.dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - back
  # -=-=-=-=-=-=-=-=-=-=BACKEND=-=-=-=-=-=-=-=-=-=-
  back:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: ./back.dockerfile
    container_name: backendD
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - backend
