version: '3.8'
# -=-=-=-=-=-=-=-=-=-=VOLUMES=-=-=-=-=-=-=-=-=-=-
volumes:
  data_deezy:
# -=-=-=-=-=-=-=-=-=-=NETWORKS=-=-=-=-=-=-=-=-=-=-
networks:
  backend_deezy:
    ipam:
      config:
        - subnet: 172.23.0.0/16
services:
  # -=-=-=-=-=-=-=-=-=-=FRONTEND=-=-=-=-=-=-=-=-=-=-
  front_deezy:
    volumes:
      - ./frontend:/app
    build:
      context: ./frontend
      dockerfile: ./front.dockerfile
    container_name: frontend_deezy
    ports:
      - "4200:4200"
    restart: unless-stopped
    networks:
      - backend_deezy
    depends_on:
      - back_deezy
  # -=-=-=-=-=-=-=-=-=-=BACKEND=-=-=-=-=-=-=-=-=-=-
  back_deezy:
    volumes:
      - ./backend:/app
    build:
      context: ./backend
      dockerfile: ./back.dockerfile
    container_name: backend_deezy
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - backend_deezy